const lists = [
  {
    id: 1,
    name: "Outdoor Chef Life",
    subscribers: 529000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQlrhkM6l1W8XZrNI9Jy5J3C4iVAGn7FwyfKf9c=s176-c-k-c0x00ffffff-no-rj",
    total_views: 57841601,
    categories: "People & Blogs",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/OutdoorChefLife",
    description:
      "Just a sushi chef out on adventures making good food from natural ingredients from the local environment.",
    featured: "false",
    contact: "taku@outdoorcheflife.com",
  },
  {
    id: 2,
    name: "Jackie Aina",
    subscribers: 3000058,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLREyrf1aAR_Cv0P7zESJhliKGzNupFofOko_tyaag=s176-c-k-c0x00ffffff-no-rj",
    total_views: 379241638,
    categories: "Fashion & Beauty",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/makeupgameonpoint",
    description: "Changing the standard of beauty, one video at a time :)",
    featured: "false",
    contact: "jackie@scalemanagement.co",
  },
  {
    id: 3,
    name: "Web Dev Simplified",
    subscribers: 669000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQpvSjzSCSo8ZKCjBZS7TRX7omb_kyQirh2zgEY=s176-c-k-c0x00ffffff-no-rj",
    total_views: 37189705,
    categories: "Science & Technology",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/WebDevSimplified",
    description:
      "Web Dev Simplified is all about teaching web development skills and techniques in an efficient and practical manner. If you are just getting started in web development Web Dev Simplified has all the tools you need to learn the newest and most popular technologies to convert you from a no stack to full stack developer. Web Dev Simplified also deep dives into advanced topics using the latest best practices for you seasoned web developers.",
    featured: "false",
    contact: "kyle@webdevsimplified.com",
  },
  {
    id: 4,
    name: "Weed 'em & Reap",
    subscribers: 665000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQ54ZRB3Z5yogTTI3PWxhWrW_zcGAKCFR5UErUsNQ=s176-c-k-c0x00ffffff-no-rj",
    total_views: 160742193,
    categories: "Howto & Style",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/Weedemandreap",
    description:
      "Born n' raised city folk, Kevin & DaNelle, along with their children Ethan & Lydia, decided in 2009 to move to a 1 acre lot in the city of Phoenix, Arizona.It was perfectly zoned for all sorts of agricultural activities so they got busy learning how to raise goats, chickens, ducks, sheep, pigs, geese, turkeys as well as learned how to garden and grow trees in their harsh desert climate.Now their daily life includes milking goats, gathering eggs, eating fresh fruits & vegetables from their garden, & harvesting fish from their pond. ",
    featured: "false",
    contact: "info@weedemandreap.com",
  },
  {
    id: 5,
    name: "Singh in USA",
    subscribers: 673000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLTDXXARcfLaUBT6xdyZajtl4Y1Z3OkglmLxQhMOlw=s176-c-k-c0x00ffffff-no-rj",
    total_views: 104407424,
    categories: "Science & Technology",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/SinghinUSA",
    description: "",
    featured: "false",
    contact: "hello@singhinusa.com",
  },
  {
    id: 6,
    name: "Clever Programmer",
    subscribers: 1000100,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLRbdv3Di8paQyrgMF_VwFXPkhwVzcW59Vgo8dTsyw=s176-c-k-c0x00ffffff-no-rj",
    total_views: 44813325,
    categories: "Science & Technology",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/CleverProgrammer",
    description:
      "You can find awesome programming lessons here! Also, expect programming tips and tricks that will take your coding skills to the next level.",
    featured: "false",
    contact: "qazi@cleverprogrammer.com",
  },
  {
    id: 7,
    name: "BMF VR",
    subscribers: 176000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLR_tcjrDPWwRANY5x5igGJECu28MOyysd0ZlsmG=s176-c-k-c0x00ffffff-no-rj",
    total_views: 52240565,
    categories: "Gaming",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/BMFVR",
    description:
      "Welcome to BMF, the unofficial home of all things Oculus Quest! Whether it's game reviews, first impressions, tips & tricks, or even random thoughts on the Oculus Quest you will find it here. The future of Virtual Reality is here with the coming of the Oculus Quest and we want to help document it and show people the amazing world that exists in VR through this amazing breakthrough.",
    featured: "false",
    contact: "matt@bmfvr.com",
  },
  {
    id: 8,
    name: "Brett Kollmann",
    subscribers: 309000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQnTQGlzlVZ9FNUHJSRZuqPH4iuyNFBx8cVqDyYnQ=s176-c-k-c0x00ffffff-no-rj",
    total_views: 43437024,
    categories: "Sport",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/BrettKollmann",
    description: "Creating the best damn NFL content on the web",
    featured: "false",
    contact: "spenser@tablerockmanagement.com",
  },
  {
    id: 9,
    name: "Parker Walbeck",
    subscribers: 16000000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQ34LD00JQ1JJiBtY7JbjzJJM15M6nsZeXLh3Biqw=s176-c-k-c0x00ffffff-no-rj",
    total_views: 96597307,
    categories: "Learning",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/ParkerWalbeck",
    description:
      "I run an online film school called Full Time Filmmaker where I act as a mentor helping filmmakers/videographers from around the world, develop their filmmaking skills and businesses.  You can check out my free 1-hour training by visiting fulltimefilmmaker.com.My objective as a content creator is to utilize the talents that God has given me to capture and share all the good in life, and to educate others on how to capture the good as well, in hope to inspire viewers to have a more positive outlook on life, and to share their talents with the world as well.",
    featured: "false",
    contact: "business@parkerwalbeck.com",
  },
  {
    id: 10,
    name: "TheGamingBeaver",
    subscribers: 3000035,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLS2qmrOAtOBAsRGSpXbBok-h-T9WWaKRl0Kk0dR=s176-c-k-c0x00ffffff-no-rj",
    total_views: 2255728261,
    categories: "Gaming",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/AGamingBeaver",
    description:
      "DINOSAURS, DINOSAURS, DINOSAURS!!Hello everyone and welcome to my youtube channel!I create content on pretty much anything that interests me but you can almost guarantee that it'll include dinosaurs in some form.",
    featured: "false",
    contact: "beaverbuisness@outlook.com",
  },
  {
    id: 11,
    name: "Justin Kan",
    subscribers: 148000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQcLgdkRCPwftdeGZX_4LsAzfyAhz6rtabAXp7B=s176-c-k-c0x00ffffff-no-rj",
    total_views: 6267578,
    categories: "People & Blogs",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/JustinKanTV",
    description:
      "What's up everyone! Welcome to my YouTube channel! I'm Justin Kan and I've been through the ups and downs in the startup world. I started Justin.tv, which morphed into Twitch and sold it to Amazon for almost $1 billion, became a partner at Y Combinator, and now I'm investing at my venture capital firm, Goat Capital, and working on my podcast, The Quest. Now, I want to share my stories, startup advice, throwback stories, life advice, behind-the-scenes content and what helped me achieve happiness here on YouTube. ",
    featured: "false",
    contact: "jen@justinkan.com",
  },
  {
    id: 12,
    name: "Entertainment Tonight",
    subscribers: 400044,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLTqXgmsFQawqF7Sisoz1o8ubEAc3to7E-IfAC0khQ=s176-c-k-c0x00ffffff-no-rj",
    total_views: 3964814027,
    categories: "Entertainment",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/entertainmenttonight",
    description:
      "ET is the Leading source of all things entertainment: Our mission is to use our unprecedented access to pop culture’s biggest stars, movies, and tv shows to deliver entertainment and celebrity news with the authority you expect everywhere you are.",
    featured: "false",
    contact: "etonlinesocial@cbs.com",
  },
  {
    id: 13,
    name: "Two Cents",
    subscribers: 616000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLSPy6N6IhyS3bQOWILaGS8n20QjShnOyNaOA04f=s176-c-k-c0x00ffffff-no-rj",
    total_views: 35955409,
    categories: "Learning",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/TwoCentsPBS",
    description:
      "TWO CENTS is an educational show about personal finance. The show is created and written by Philip Olson, Julia Lorenz-Olson, Andrew Matthews, and Katie Graham.",
    featured: "false",
    contact: "twocentspbs@gmail.com",
  },
  {
    id: 14,
    name: "Linda Raynier",
    subscribers: 849000,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLT3RuqmbsDiLDRNOV9839LR_ULPwCIvottfTRPc=s176-c-k-c0x00ffffff-no-rj",
    total_views: 52940200,
    categories: "Learning",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/LindaRaynier",
    description:
      "Hi! I'm Linda and I'm all about sharing practical, useful and heart-centered advice on how to have the career that's meant for you, while being your 100% authentic self. You and I both know that you're meant to do something bigger...so I'm going to guide you to that! ",
    featured: "false",
    contact: "linda@lindaraynier.com",
  },
  {
    id: 15,
    name: "Marques Brownlee",
    subscribers: 14000700,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLR-pT_JEsz_hcaA4Gjx8DHcqJ8mS42aTRqcVy6P7w=s176-c-k-c0x00ffffff-no-rj",
    total_views: 2690609537,
    categories: "Science & Technology",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/mkbhd",
    description:
      "MKBHD: Quality Tech Videos | YouTuber | Geek | Consumer Electronics | Tech Head | Internet Personality!",
    featured: "false",
    contact: "marques@mkbhd.com",
  },
  {
    id: 16,
    name: "Jasmine Brown",
    subscribers: 200039,
    image:
      "https://yt3.ggpht.com/VvJTiOVgehbqr6lBA2dC_PZ93Bll36lUzTDsyogcvTo8Gh-cbUBssj7j6UhpcIt7Aw4ey0ZisFk=s176-c-k-c0x00ffffff-no-rj",
    total_views: 177067628,
    categories: "Fashion & Beauty",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/JasmineBrown",
    description: "Thanks for watching my channel!!",
    featured: "false",
    contact: "vanessa@jamesgrant.com",
  },
  {
    id: 17,
    name: "AmandaRachLee",
    subscribers: 2000070,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLRMD0558z1YVUJHugCm-msgv7RbPzFyWaa9qGsF6g=s176-c-k-c0x00ffffff-no-rj",
    total_views: 168892960,
    categories: "Fashion & Beauty",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/amandarachlee",
    description:
      " Making my way through life with a pencil in hand and creativity in mind. Subscribe for new videos every week!",
    featured: "false",
    contact: "business@amandarachlee.com",
  },
  {
    id: 18,
    name: "TopTenz",
    subscribers: 1000920,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLSdn0eVcgSLp35YGznKzWH6uMLpatz26A1wMSKfdA=s176-c-k-c0x00ffffff-no-rj",
    total_views: 675274655,
    categories: "People & Blogs",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/ToptenzNettop10",
    description:
      " Brand new videos 7 days a week! Videos are published at  6pm Eastern Time every day!",
    featured: "false",
    contact: "sponsors@toptenz.net",
  },
  {
    id: 19,
    name: "Arden Rose",
    subscribers: 1000045,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLRDEdBBqEDFXqv5qXYir1-ksmAFi47Q9tNr9975hQ=s176-c-k-c0x00ffffff-no-rj",
    total_views: 146143499,
    categories: "People & Blogs",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/ardenrose",
    description:
      "Hey guys! Thanks for checking out my channel, and I hope you like my videos! Subscribe, and I'll give you fresh baked cookies for the next 20 years. ",
    featured: "false",
    contact: "bashley@settebelloentertainment.com",
  },
  {
    id: 20,
    name: "Magic Murray",
    subscribers: 1000077,
    image:
      "https://yt3.ggpht.com/ytc/AKedOLQ8mHOoPelyDd7nxIn7f5LrDu2jWGzk5uS09_Gh=s176-c-k-c0x00ffffff-no-rj",
    total_views: 224050154,
    categories: "Comedy",
    rate: 2000,
    availability: false,
    channelUrl: "https://www.youtube.com/c/magicmurray/",
    description:
      " Murray SawChuck 'Celebrity Magician'. Magician, Prankster, Illusionist, Comedian as seen on Pawn Stars, America's Got Talent, Comedy Central. Weekly uploads of magic prank videos, every Wednesday. ",
    featured: "false",
    contact: "MagicMurraySawChuck@gmail.com",
  },
];

export default lists;
